List offer = [
  {
    'add': 'Biryani',
    'name': '40% OFF',
    'off': 'ABOVE ₹189',
    'rate': 3.7,
    'img': 'assets/images/offer/biryani.jpeg',
    'foodname': 'Tawakal\nBiryani Center',
    'food': 'Tawakal Biryani Center',
    'duration': '20-30 mins',
  },
  {
    'add': 'Street Food',
    'km': 'Dindoli - 1.6 km',
    'name': '44% OFF',
    'off': 'ABOVE ₹119',
    'rate': 2.5,
    'img': 'assets/images/offer/bhature.jpg',
    'foodname': 'Punjabi\nDhaba',
    'food': 'Punjabi Dhaba',
    'duration': '40-50 mins',
  },
  {
    'km': 'Athwa - 7.7 km',
    'add': 'Cakes & Pastries',
    'name': '21% OFF',
    'img': 'assets/images/offer/cake.jpeg',
    'off': 'UPTO ₹239',
    'rate': 1.2,
    'foodname': 'Sainath Live\nCake',
    'food': 'Sainath Live Cake',
    'duration': '15-20 mins',
  },
  {
    'add': 'Chinese',
    'km': 'Salabatpura - 6.2 km',
    'name': '20% OFF',
    'off': 'UPTO ₹349',
    'rate': 4.7,
    'img': 'assets/images/offer/chinese.jpeg',
    'foodname': 'Chinese',
    'food': 'Chinese',
    'duration': '25-35 mins\n',
  },
  {
    'km': 'Udhna Gam - 2.6 km',
    'add': 'Chocolate Shake',
    'name': '32% OFF',
    'off': 'UPTO ₹110',
    'rate': 4.1,
    'img': 'assets/images/offer/chocolate_shake.jpeg',
    'foodname': 'Chocolate Milk\nShake',
    'food': 'Chocolate Milk Shake',
    'duration': '20-30 mins',
  },
  {
    'km': 'New Textile Market - 7.2 km',
    'add': 'Pizza',
    'name': '49% OFF',
    'off': 'ABOVE ₹239',
    'rate': 3.3,
    'img': 'assets/images/offer/pizza.jpg',
    'foodname': 'Pizza Castele',
    'food': 'Pizza Castele',
    'duration': '15-20 mins\n',
  },
  {
    'add': 'North Indian, Lassi',
    'km': 'Sion - 2.2 km',
    'name': '50% OFF',
    'off': 'UPTO ₹100',
    'rate': 4.6,
    'img': 'assets/images/offer/lassi.jpeg',
    'foodname': 'Jassi Da\nDhaba',
    'food': 'Jassi Da Dhaba',
    'duration': '35-45 mins',
  },
  {
    'add': 'Street Food',
    'km': 'Udhna Gam - 3.9 km',
    'name': '43% OFF',
    'img': 'assets/images/offer/role.jpeg',
    'rate': 3.5,
    'off': 'ABOVE ₹349',
    'foodname': 'Madina\nHotel',
    'food': 'Madina Hotel',
    'duration': '40-45 mins',
  },
  {
    'add': 'Fast Food',
    'km': 'Athwa - 3.9 km',
    'name': '43% OFF',
    'img': 'assets/images/offer/burger.jpeg',
    'rate': 3.5,
    'off': 'ABOVE ₹299',
    'foodname': 'Subway',
    'food': 'Subway',
    'duration': '50-55 mins\n',
  },
  {
    'add': 'South Indian',
    'km': 'Umarwada - 5.0 km',
    'name': '60% OFF',
    'img': 'assets/images/offer/pavbhaji.jpeg',
    'rate': 4.2,
    'off': 'ABOVE ₹120',
    'foodname': 'Mahesh Pav\nBhaji',
    'food': 'Mahesh Pav Bhaji',
    'duration': '40-45 mins',
  },
  {
    'add': 'Street Food',
    'km': 'Udhana Gam - 5.0 km',
    'name': '22% OFF',
    'img': 'assets/images/offer/samosa.jpeg',
    'rate': 6.2,
    'off': 'ABOVE ₹50',
    'foodname': 'Samosa',
    'food': 'Samosa',
    'duration': '20-25 mins\n',
  },
  {
    'add': 'Gujarati, Snacks',
    'km': 'City Light - 2.5 km',
    'name': '25% OFF',
    'off': 'UPTO ₹100',
    'rate': 4.6,
    'img': 'assets/images/offer/dhokala.jpeg',
    'foodname': 'Surti Dhokla\nHouse',
    'food': 'Surti Dhokla House',
    'duration': '20-30 mins',
  },
  {
    'add': 'Rajasthani, Street Food',
    'km': 'Ghod Dod Road - 3.5 km',
    'name': '30% OFF',
    'off': 'UPTO ₹150',
    'rate': 4.2,
    'img': 'assets/images/offer/kachori.jpeg',
    'foodname': 'Jaipur Kachori',
    'food': 'Jaipur Kachori',
    'duration': '25-35 mins\n',
  },
  {
    'add': 'Street Food',
    'km': 'Udhana Gam - 3.5 km',
    'name': '15% OFF',
    'off': 'UPTO ₹45',
    'rate': 3.7,
    'img': 'assets/images/offer/momos.jpeg',
    'foodname': 'Momos',
    'food': 'Momos',
    'duration': '20-25 mins\n',
  },
  {
    'add': 'Cafe, Beverages',
    'km': 'Rustampura - 3.5 km',
    'name': '15% OFF',
    'off': 'UPTO ₹80',
    'rate': 4.4,
    'img': 'assets/images/offer/pasta.jpeg',
    'foodname': "Pasta",
    'food': "Pasta",
    'duration': '40-45 mins\n',
  },
  {
    'add': 'Sandwich, Beverages, Cafe',
    'km': 'Ghod Dod Road - 3.5 km',
    'name': '25% OFF',
    'off': 'UPTO ₹100',
    'rate': 2.5,
    'img': 'assets/images/offer/sandwich.jpeg',
    'foodname': "Grilled Cheese\nSandwich",
    'food': "Cheese Sandwich",
    'duration': '25-35 mins',
  },
  {
    'add': 'South Indian Food',
    'km': 'Udhana - 3.5 km',
    'name': '30% OFF',
    'off': 'UPTO ₹100',
    'rate': 5.4,
    'img': 'assets/images/offer/dosa.jpeg',
    'foodname': "Dosa",
    'food': "Dosa",
    'duration': '25-35 mins\n',
  },
];
List reversedList = offer.reversed.toList();
